DROP DATABASE IF EXISTS taaza;
CREATE DATABASE taaza;
USE taaza;
CREATE TABLE feeds (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) CHARACTER SET 'utf8mb4' NOT NULL,
  description VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL DEFAULT "Rss Feed",
  url VARCHAR(255) NOT NULL,
  timestamp_added DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_fetched DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00',
  refresh_interval_seconds INTEGER NOT NULL DEFAULT 1200,
  status TINYINT NOT NULL DEFAULT 0,
  favicon_file VARCHAR(255) NOT NULL DEFAULT 'default.png',
  check_new TINYINT NOT NULL DEFAULT 0,
  upstream_etag VARCHAR(255),
  upstream_last_modified VARCHAR(255)
);
CREATE TABLE users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR (255) CHARACTER SET 'utf8mb4' UNIQUE NOT NULL,
  email VARCHAR (255) UNIQUE NOT NULL,
  pw VARCHAR (255) NOT NULL,
  timestamp_added DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE user_feeds (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  feed_id BIGINT UNSIGNED NOT NULL,
  favorite_index INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT `fk_user_feeds_users` FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT `fk_user_feeds_feeds` FOREIGN KEY (feed_id) REFERENCES feeds(id) ON DELETE CASCADE,
  UNIQUE `unique_index` (user_id, feed_id)
);
CREATE TABLE pending_user_tokens (
  id INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  pw VARCHAR(255) NOT NULL,
  token VARCHAR(255) NOT NULL,
  expiry_datetime DATETIME NOT NULL,
  entered_datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE pending_pwreset_tokens (
  id INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  token VARCHAR(255) NOT NULL,
  expiry_datetime DATETIME NOT NULL,
  entered_datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE posts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  feed_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
  url VARCHAR(255) NOT NULL,
  extra_urls JSON NOT NULL,
  pub_date DATETIME NOT NULL,
  /* status: 1 new, 0 old  */
  status TINYINT NOT NULL DEFAULT 1,
  CONSTRAINT `fk_posts_feeds` FOREIGN KEY (feed_id) REFERENCES feeds(id),
  CHECK (JSON_VALID(extra_urls))
);